version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - revive
    - gosec
  settings:
    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: context-keys-type
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: exported
        - name: increment-decrement
        - name: var-naming
        - name: var-declaration
        - name: package-comments
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: empty-block
        - name: superfluous-else
        - name: unused-parameter
        - name: unreachable-code
        - name: redefines-builtin-id
    gosec:
      severity: medium
      confidence: medium
  exclusions:
    rules:
      - linters:
          - revive
        path: "internal/(version|metrics)/"
        text: "var-naming: avoid package names"

formatters:
  enable:
    - gofumpt
    - goimports
    - golines
  settings:
    gofumpt:
      module-path: &module-name github.com/danroc/wol-relay
      extra-rules: true
    goimports:
      local-prefixes:
        - *module-name
    golines:
      max-len: 88
      shorten-comments: true
